name: portfolio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  dio: ^5.4.0
  shared_preferences: ^2.0.15
  device_info_plus: ^11.1.1

  fluttertoast: ^8.1.2
  url_launcher: ^6.3.1
  timelines_plus: ^1.0.6
  #
  pdf: ^3.11.1
  printing: ^5.13.4
  flutter_pdfview: ^1.3.4
  file_picker: ^10.1.2
  path_provider: ^2.0.12
  #
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  particles_network: ^1.6.0
  flutter_html: ^3.0.0
  clipboard: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/languages/
    - assets/activity/
    - assets/edu/
    - assets/company/
    #
    - assets/icons/
    - assets/icons/social/
    - assets/icons/skill/
    - assets/icons/communicate/
    - assets/icons/platform/
    - assets/icons/projects/
    #
    - assets/images/
    - assets/resume/
    - assets/data/languages.json
    - assets/data/home_info.json
    - assets/data/other_social_media.json
    - assets/resume/resume_mukta.pdf

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  
    - family: bangla
      fonts:
        - asset: assets/fonts/bengali/NotoSerifBengali-Bold.ttf
        - asset: assets/fonts/bengali/NotoSerifBengali-Regular.ttf
